# -*- coding: utf-8 -*-
"""vF_HODL Final Project.ipynb のコピー

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kExHJz5bmSADfiRGfozRTGmJrXyJ2Rum

# Part 1: Structured Data (Tabular Churn Prediction)

We predict customer churn using structured tabular features such as tenure, contract type, and monthly charges, and compare a classical model like logistic regression with deep learning models such as feedforward neural networks to evaluate whether increased model complexity improves churn prediction.
"""

import numpy as np
import random
import tensorflow as tf

SEED = 42
np.random.seed(SEED)
random.seed(SEED)
tf.random.set_seed(SEED)

import os

os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"] = "1"

tf.keras.utils.set_random_seed(SEED)
tf.config.experimental.enable_op_determinism()

# ===============================
# Libraries
# ===============================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    roc_curve
)
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

df.info()

df = df.drop(columns=["customerID"])

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df = df.dropna()

df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

print("Final data shape:", df.shape)

print("Churn distribution:")
print(df["Churn"].value_counts(normalize=True))

# Tenure vs Churn
sns.boxplot(x="Churn", y="tenure", data=df)
plt.title("Tenure by Churn")
plt.show()

# Contract vs Churn
contract_churn = pd.crosstab(
    df["Contract"], df["Churn"], normalize="index"
)
contract_churn.plot(kind="bar", stacked=True)
plt.title("Churn Rate by Contract Type")
plt.show()

# MonthlyCharges vs Churn
sns.boxplot(x="Churn", y="MonthlyCharges", data=df)
plt.show()

# Correlation
numeric_cols = ["tenure", "MonthlyCharges", "TotalCharges"]
sns.heatmap(df[numeric_cols].corr(), annot=True)
plt.show()

sns.scatterplot(x="tenure", y="TotalCharges", data=df)
plt.title("Tenure vs TotalCharges")
plt.show()

df_encoded = pd.get_dummies(df, drop_first=True)

feature_names = df_encoded.drop(columns=["Churn"]).columns.tolist()

X = df_encoded.drop(columns=["Churn"])
y = df_encoded["Churn"]

print("Number of features:", len(feature_names))

X_train_df, X_test_df, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=SEED,
    stratify=y
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train_df)
X_test = scaler.transform(X_test_df)

print("Feature count check:",
      X_train.shape[1] == len(feature_names))

log_base = LogisticRegression(
    max_iter=1000,
    random_state=SEED
)

log_base.fit(X_train, y_train)

y_prob_base = log_base.predict_proba(X_test)[:, 1]

print("Baseline AUC:",
      roc_auc_score(y_test, y_prob_base))

print(classification_report(
    y_test,
    log_base.predict(X_test)
))

log_weight = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=SEED
)

log_weight.fit(X_train, y_train)

y_prob_weight = log_weight.predict_proba(X_test)[:, 1]

print("Weighted AUC:",
      roc_auc_score(y_test, y_prob_weight))

print(classification_report(
    y_test,
    log_weight.predict(X_test)
))

X_reduced = X.drop(columns=["TotalCharges"])

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_reduced, y,
    test_size=0.2,
    random_state=SEED,
    stratify=y
)

scaler_r = StandardScaler()
X_train_r = scaler_r.fit_transform(X_train_r)
X_test_r = scaler_r.transform(X_test_r)

log_reduced = LogisticRegression(
    max_iter=1000,
    random_state=SEED
)

log_reduced.fit(X_train_r, y_train_r)

print("Reduced AUC:",
      roc_auc_score(
          y_test_r,
          log_reduced.predict_proba(X_test_r)[:, 1]
      ))

log_both = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=SEED
)

log_both.fit(X_train_r, y_train_r)

print("Weighted + Reduced AUC:",
      roc_auc_score(
          y_test_r,
          log_both.predict_proba(X_test_r)[:, 1]
      ))

threshold = 0.3
y_pred_thresh = (y_prob_base >= threshold).astype(int)

print("Threshold=0.3")
print(classification_report(y_test, y_pred_thresh))

fpr, tpr, _ = roc_curve(y_test, y_prob_base)

plt.plot(fpr, tpr)
plt.plot([0,1],[0,1],"--")
plt.title("ROC Curve")
plt.show()

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

# ===============================
# Best Model Tracker
# ===============================
best_model = None
best_model_name = None
best_auc = 0

def build_basic(lr=0.001):
    model = keras.Sequential([
        keras.Input(shape=(X_train.shape[1],)),
        layers.Dense(32, activation="relu"),
        layers.Dense(16, activation="relu"),
        layers.Dense(1, activation="sigmoid")
    ])
    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss="binary_crossentropy",
        metrics=[keras.metrics.AUC(name="auc")]
    )
    return model

basic_model = build_basic()

early_stop = EarlyStopping(
    monitor="val_auc",
    mode="max",
    patience=5,
    restore_best_weights=True
)

basic_model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1,
    shuffle=False
)

print("Basic MLP AUC:",
      basic_model.evaluate(X_test, y_test, verbose=0)[1])

basic_auc = basic_model.evaluate(X_test, y_test, verbose=0)[1]

if basic_auc > best_auc:
    best_auc = basic_auc
    best_model = basic_model
    best_model_name = "Basic MLP"
print("Current Best Model:",best_model_name)

lrs = [0.01, 0.005, 0.001, 0.0005,0.0004, 0.0003,0.0002, 0.0001]

for lr in lrs:
    model = build_basic(lr)
    model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=50,
        batch_size=32,
        callbacks=[early_stop],
        verbose=0,
        shuffle=False
    )
    auc_value = model.evaluate(X_test, y_test, verbose=0)[1]

    print("lr:", lr, "AUC:", auc_value)

    if auc_value > best_auc:
        best_auc = auc_value
        best_model = model
        best_model_name = f"Basic MLP (lr={lr})"
print("Current Best Model:",best_model_name)

dropout_rates = [0.2, 0.3, 0.4, 0.5, 0.6]

for rate in dropout_rates:
    model = build_regularized(
        lr=0.0003,
        drop_rate=rate
    )
    model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=100,
        batch_size=32,
        callbacks=[early_stop],
        verbose=0,
        shuffle=False
    )

    auc_value = model.evaluate(X_test, y_test, verbose=0)[1]

    print("Dropout:", rate, "AUC:", auc_value)

    if auc_value > best_auc:
        best_auc = auc_value
        best_model = model
        best_model_name = f"Regularized MLP (dropout={rate})"
print("Current Best Model:",best_model_name)

def build_deep(lr=0.0003):
    model = keras.Sequential([
        keras.Input(shape=(X_train.shape[1],)),
        layers.Dense(64, activation="relu"),
        layers.Dense(32, activation="relu"),
        layers.Dense(16, activation="relu"),
        layers.Dense(1, activation="sigmoid")
    ])
    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss="binary_crossentropy",
        metrics=[keras.metrics.AUC(name="auc")]
    )
    return model

deep_model = build_deep()

deep_model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1,
    shuffle=False
)

print("Deep Model AUC:",
      deep_model.evaluate(X_test, y_test, verbose=0)[1])

deep_auc = deep_model.evaluate(X_test, y_test, verbose=0)[1]

if deep_auc > best_auc:
    best_auc = deep_auc
    best_model = deep_model
    best_model_name = "Deep MLP"
print("Current Best Model:",best_model_name)

from tensorflow.keras import regularizers

def build_regularized(lr=0.0003, drop_rate=0.3):
    model = keras.Sequential([
        keras.Input(shape=(X_train.shape[1],)),
        layers.Dense(32, activation="relu",
                     kernel_regularizer=regularizers.l2(0.001)),
        layers.Dropout(drop_rate, seed=SEED),
        layers.Dense(16, activation="relu",
                     kernel_regularizer=regularizers.l2(0.001)),
        layers.Dropout(drop_rate, seed=SEED),
        layers.Dense(1, activation="sigmoid")
    ])
    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss="binary_crossentropy",
        metrics=[keras.metrics.AUC(name="auc")]
    )
    return model

reg_model = build_regularized()

reg_model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1,
    shuffle=False
)

print("Regularized MLP AUC:",
      reg_model.evaluate(X_test, y_test, verbose=0)[1])

reg_auc = reg_model.evaluate(X_test, y_test, verbose=0)[1]

if reg_auc > best_auc:
    best_auc = reg_auc
    best_model = reg_model
    best_model_name = "Regularized MLP"
print("Current Best Model:",best_model_name)

import shap

np.random.seed(SEED)

print("Best model selected:", best_model_name)
print("Best AUC:", best_auc)

def predict_fn(X):
    return best_model.predict(X, verbose=0).flatten()

background_size = 100
sample_size = 200

idx_background = np.random.choice(
    X_train.shape[0],
    background_size,
    replace=False
)

X_background = X_train[idx_background]
X_sample = X_test[:sample_size]

X_sample_df = pd.DataFrame(
    X_sample,
    columns=feature_names
)

explainer = shap.KernelExplainer(
    predict_fn,
    X_background
)

shap_values = explainer.shap_values(X_sample)

if isinstance(shap_values, list):
    shap_values = shap_values[0]

plt.figure(figsize=(8,6))
shap.summary_plot(
    shap_values,
    X_sample_df,
    max_display=15,
    show=False
)
plt.show()

"""## Part 2: NLP analysis of reviews

We analyze customer reviews as unstructured text data. We first use sentiment as a proxy for churn likelihood, then classify complaint categories to identify the likely reason for dissatisfaction.
"""

import os
os.environ['KERAS_BACKEND'] = 'tensorflow'

import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

keras.utils.set_random_seed(42)

df = pd.read_csv('mint_mobile_reviews_classified.csv')
df = df[['text', 'rating', 'sentiment', 'complaint_category']].copy()

print(df.shape)
display(df.head())

print(df['sentiment'].value_counts(dropna=False))
print(df['complaint_category'].value_counts(dropna=False))

"""Using sentiment from rating as a proxy for churn likelihood because negative reviews indicate dissatisfied customers who are likely to churn. We label customers who are likely to churn as 1 and those who are satisfied and unlikely to churn as 0."""

# Create the 'label' column based on 'sentiment'
df['label'] = df['sentiment'].apply(lambda x: 1 if x == 'Negative' else (0 if x == 'Positive' else None))

display(df.head())

test_val_df = df.sample(frac=0.5, random_state=42)
train_df = df.drop(test_val_df.index)

val_df = test_val_df.sample(frac=0.5, random_state=43)
test_df = test_val_df.drop(val_df.index)

# Get the labels for the train/test/validation sets
y_train = train_df['label'].to_numpy().astype(np.float32)
y_test = test_df['label'].to_numpy().astype(np.float32)
y_val = val_df['label'].to_numpy().astype(np.float32)

print(f'Train set shape: {train_df.shape}')
print(f'Test set shape: {test_df.shape}')
print(f'Validation set shape: {val_df.shape}')

"""We are applying the Bag-Of-Words method for converting every review into a numerical representation (vector) that can be passed throught a neural network. Then, we will create a neural network to classify the articles into `likely to churn` or `not likely to churn`.

We will begin by applying the STIE process (standardize, tokenize, index, encode) into our articles.
"""

max_tokens = 5000 # size of vocabulary space
text_vectorization = keras.layers.TextVectorization(
    max_tokens=max_tokens,
    standardize='lower_and_strip_punctuation', # default
    split='whitespace', # default
    output_mode="multi_hot",
)

text_vectorization.adapt(train_df['text'])
text_vectorization.get_vocabulary()[:20]

#apply function to get multihot encodings
X_train = text_vectorization(train_df['text'])
X_val = text_vectorization(val_df['text'])
X_test = text_vectorization(test_df['text'])

pd.DataFrame(X_train, columns=text_vectorization.get_vocabulary()).astype(int)

inputs = keras.layers.Input(shape=(max_tokens, ), name='input')
x = keras.layers.Dense(128, activation="relu", name='hidden')(inputs)
outputs = keras.layers.Dense(1, activation="sigmoid", name='output')(x)
bow_model = keras.Model(inputs, outputs, name='simple_bow')

bow_model.summary()

bow_model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

# Train the model on the training set
bow_model.fit(x=X_train, y=y_train,
          validation_data=(X_val, y_val),
          epochs=10,
          batch_size=32)

print('Test Accuracy is', bow_model.evaluate(X_test, y_test)[1])

"""Simple Bag of Words model Test Accuracy is 86.96%. We next strengthen the bag-of-words baseline by using count encoding with bigrams, allowing the model to capture both word frequency and short phrases rather than only single-word presence."""

max_tokens = 20000

text_vectorization_count = keras.layers.TextVectorization(
    max_tokens=max_tokens,
    standardize='lower_and_strip_punctuation',
    split='whitespace',
    ngrams=2,
    output_mode='count'
)

text_vectorization_count.adapt(train_df['text'])

X_train_count = text_vectorization_count(train_df['text'])
X_val_count = text_vectorization_count(val_df['text'])
X_test_count = text_vectorization_count(test_df['text'])

inputs = keras.layers.Input(shape=(max_tokens,), name='input')
x = keras.layers.Dense(128, activation='relu')(inputs)
x = keras.layers.Dropout(0.3)(x)
x = keras.layers.Dense(64, activation='relu')(x)
outputs = keras.layers.Dense(1, activation='sigmoid')(x)

bow_count_model = keras.Model(inputs, outputs, name='sentiment_bow_count_bigram')

bow_count_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_bow_count = bow_count_model.fit(
    x=X_train_count,
    y=y_train,
    validation_data=(X_val_count, y_val),
    epochs=15,
    batch_size=32,
    callbacks=[keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=3,
        restore_best_weights=True
    )],
    verbose=1
)

print('Sentiment BoW Count+Bigram Test Accuracy:',
      bow_count_model.evaluate(X_test_count, y_test, verbose=0)[1])

"""The improved bag-of-words model achieved a test accuracy of 89.49, outperforming the simpler unigram baseline. Finally, we evaluate a pretrained BERT-based model to test whether a transformer architecture can better capture semantic context in customer reviews than bag-of-words representations."""

import tensorflow as tf
import keras_hub

tf.config.optimizer.set_jit(False)

preprocessor = keras_hub.models.BertPreprocessor.from_preset(
    "bert_base_en_uncased",
    sequence_length=128
)

backbone = keras_hub.models.BertBackbone.from_preset(
    "bert_base_en_uncased"
)

text_input = keras.Input(shape=(), dtype=tf.string, name="text")
x = preprocessor(text_input)
x = backbone(x)["pooled_output"]
x = keras.layers.Dropout(0.2)(x)
output = keras.layers.Dense(1, activation="sigmoid")(x)

bert_sentiment_model = keras.Model(text_input, output)

bert_sentiment_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=2e-5),
    loss="binary_crossentropy",
    metrics=["accuracy"],
    jit_compile=False
)

x_train_text = train_df['text'].fillna('').astype(str).to_numpy()
x_val_text = val_df['text'].fillna('').astype(str).to_numpy()
x_test_text = test_df['text'].fillna('').astype(str).to_numpy()

history_bert_sentiment = bert_sentiment_model.fit(
    x=x_train_text,
    y=y_train.astype("float32"),
    validation_data=(x_val_text, y_val.astype("float32")),
    epochs=3,
    batch_size=4,
    callbacks=[keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=1,
        restore_best_weights=True
    )],
    verbose=1
)

print(
    "Sentiment BERT Test Accuracy:",
    bert_sentiment_model.evaluate(x_test_text, y_test.astype("float32"), verbose=0)[1]
)

"""The BERT-based model achieved a test accuracy of 0.9123, outperforming both bag-of-words baselines. This suggests that contextual language representations provide additional value for text-based churn-signal detection.

**Sentiment Classification Summary**

- Simple BoW accuracy: 0.8696
- BoW with count + bigrams accuracy: 0.8950
- BERT accuracy: 0.9123

As text models become more expressive, performance improves. Unlike the tabular churn task, the text-based sentiment task benefits more clearly from deep learning.

## Identifying complaint reason category for negative reviews
We next classify the underlying reason for dissatisfaction from review text. This is a multiclass NLP task with six complaint categories: Network & Coverage, Number Porting & Account Setup, Data Speed & Performance, Billing & Pricing, Customer Service, and App, Website & Account Management. Because the categories are imbalanced, we evaluate performance using both accuracy and macro F1.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, f1_score
import numpy as np

# Complaint-category dataset
df_categories = df[['text', 'complaint_category']].copy()
df_categories = df_categories.dropna()
df_categories = df_categories[df_categories['complaint_category'] != 'Uncategorized'].copy()

# Encode labels
label_encoder = LabelEncoder()
df_categories['category_label'] = label_encoder.fit_transform(df_categories['complaint_category'])

num_classes = len(label_encoder.classes_)
print("Number of unique complaint categories:", num_classes)
print("Original categories:", list(label_encoder.classes_))

# Stratified split: 70/15/15
train_df_cat, temp_df_cat = train_test_split(
    df_categories,
    test_size=0.30,
    random_state=42,
    stratify=df_categories['category_label']
)

val_df_cat, test_df_cat = train_test_split(
    temp_df_cat,
    test_size=0.50,
    random_state=43,
    stratify=temp_df_cat['category_label']
)

y_train_cat = train_df_cat['category_label'].to_numpy().astype(np.int32)
y_val_cat = val_df_cat['category_label'].to_numpy().astype(np.int32)
y_test_cat = test_df_cat['category_label'].to_numpy().astype(np.int32)

print(f"Train set shape: {train_df_cat.shape}")
print(f"Validation set shape: {val_df_cat.shape}")
print(f"Test set shape: {test_df_cat.shape}")

display(train_df_cat.head())

max_tokens_cat = 20000

text_vectorization_cat = keras.layers.TextVectorization(
    max_tokens=max_tokens_cat,
    standardize='lower_and_strip_punctuation',
    split='whitespace',
    ngrams=2,
    output_mode='count'
)

text_vectorization_cat.adapt(train_df_cat['text'])

X_train_cat = text_vectorization_cat(train_df_cat['text'])
X_val_cat = text_vectorization_cat(val_df_cat['text'])
X_test_cat = text_vectorization_cat(test_df_cat['text'])

inputs_cat = keras.layers.Input(shape=(max_tokens_cat,), name='input_category')
x_cat = keras.layers.Dense(128, activation='relu', name='hidden_1_cat')(inputs_cat)
x_cat = keras.layers.Dropout(0.3)(x_cat)
x_cat = keras.layers.Dense(64, activation='relu', name='hidden_2_cat')(x_cat)
outputs_cat = keras.layers.Dense(num_classes, activation='softmax', name='output_category')(x_cat)

bow_model_cat = keras.Model(inputs_cat, outputs_cat, name='complaint_category_bow')

bow_model_cat.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_cat = bow_model_cat.fit(
    X_train_cat,
    y_train_cat,
    validation_data=(X_val_cat, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=3,
        restore_best_weights=True
    )],
    verbose=1
)

test_probs_cat = bow_model_cat.predict(X_test_cat)
test_pred_cat = np.argmax(test_probs_cat, axis=1)

print("Complaint Category BoW Accuracy:",
      bow_model_cat.evaluate(X_test_cat, y_test_cat, verbose=0)[1])
print("Complaint Category BoW Macro F1:",
      f1_score(y_test_cat, test_pred_cat, average='macro'))
print(classification_report(
    y_test_cat,
    test_pred_cat,
    target_names=label_encoder.classes_
))

"""The bag-of-words complaint-category model achieved a test accuracy of 0.6893 and a macro F1 score of 0.6027. Performance is strongest on larger categories such as Customer Service and Network & Coverage, while weaker on smaller classes such as App, Website & Account Management.

We then test a BERT-based classifier to evaluate whether contextual language representations improve complaint-category prediction relative to the bag-of-words baseline.
"""

import tensorflow as tf
import keras
import keras_hub
import numpy as np
from sklearn.metrics import classification_report, f1_score

tf.config.optimizer.set_jit(False)

# Clean text + labels
x_train_cat_text = train_df_cat['text'].fillna('').astype(str).to_numpy()
x_val_cat_text = val_df_cat['text'].fillna('').astype(str).to_numpy()
x_test_cat_text = test_df_cat['text'].fillna('').astype(str).to_numpy()

y_train_cat = np.array(y_train_cat).astype("int32")
y_val_cat = np.array(y_val_cat).astype("int32")
y_test_cat = np.array(y_test_cat).astype("int32")

preprocessor_cat = keras_hub.models.BertPreprocessor.from_preset(
    "bert_base_en_uncased",
    sequence_length=128
)

backbone_cat = keras_hub.models.BertBackbone.from_preset(
    "bert_base_en_uncased"
)

text_input_cat = keras.Input(shape=(), dtype=tf.string, name="text")
x_cat = preprocessor_cat(text_input_cat)
x_cat = backbone_cat(x_cat)["pooled_output"]
x_cat = keras.layers.Dropout(0.3)(x_cat)
output_cat = keras.layers.Dense(num_classes, activation="softmax")(x_cat)

bert_cat_model = keras.Model(text_input_cat, output_cat, name="complaint_category_bert")

bert_cat_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=2e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'],
    jit_compile=False
)

history_bert_cat = bert_cat_model.fit(
    x=x_train_cat_text,
    y=y_train_cat,
    validation_data=(x_val_cat_text, y_val_cat),
    epochs=4,
    batch_size=4,
    callbacks=[keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=1,
        restore_best_weights=True
    )],
    verbose=1
)

bert_cat_probs = bert_cat_model.predict(x_test_cat_text)
bert_cat_pred = np.argmax(bert_cat_probs, axis=1)

print("Complaint Category BERT Accuracy:",
      bert_cat_model.evaluate(x_test_cat_text, y_test_cat, verbose=0)[1])
print("Complaint Category BERT Macro F1:",
      f1_score(y_test_cat, bert_cat_pred, average='macro'))
print(classification_report(
    y_test_cat,
    bert_cat_pred,
    target_names=label_encoder.classes_
))

"""The BERT complaint-category model achieved a test accuracy of 0.6939 and a macro F1 score of 0.6241. While the gain in accuracy is modest, the improvement in macro F1 indicates somewhat better performance across imbalanced classes.

**Complaint Category Classification Summary**

- BoW accuracy: 0.6893
- BoW macro F1: 0.6027
- BERT accuracy: 0.6939
- BERT macro F1: 0.6241

BERT provides only a small improvement in accuracy, but a more meaningful improvement in macro F1, suggesting better balanced performance across categories.

In the original tabular churn prediction task, deep learning provided little advantage over logistic regression. In contrast, for the text-based review tasks, model performance improved as the NLP approach became more expressive: from simple bag-of-words, to count + bigrams, to BERT. This suggests that deep learning is more useful for unstructured text data than for relatively simple structured tabular churn prediction.
"""